#!/usr/bin/sh

#TODO: do this in go
if [ $TERM != 'linux' ]; then
	echo 'Term Boy can only be run in a virtual console'
	echo '(Try pressing CTRL+ALT+F2)'
	exit 1
fi

#TODO: save and restore font
setfont -h4 && termboy-go $1; setfont
